name: Trigger Ubuntu20.04 CI test test
run-name: Ubuntu20.04 - ${{ github.event.pull_request.title }}
on:
  pull_request:
    types: labeled
    # paths:
    # - 'images/linux/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2004:
    if: contains(github.event.pull_request.labels.*.name, 'CI ubuntu-all') || contains(github.event.pull_request.labels.*.name, 'CI ubuntu-2004')
    uses: ./.github/workflows/trigger-remote-reusable-workflow.yml
    with:
      repo_owner: 'shamil-mubarakshin'
      repo_name: 'azure-workflows'
      image_type: 'ubuntu2004'
    secrets: inherit
