run-name: Ubuntu20.04 - ${{ github.event.pull_request.title }}
on:
  # workflow_dispatch:
  #   inputs:
  #     CUSTOM_REPOSITORY:
  #       description: 'Custom repository (owner/repo)'
  #       required: false
  #     CUSTOM_REPOSITORY_COMMIT_HASH:
  #       description: 'Commit hash'
  #       required: false
  pull_request_target:
    types: labeled
    # paths:
    # - 'images/linux/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2004:
    if: contains(github.event.pull_request.labels.*.name, 'CI ubuntu-all') || contains(github.event.pull_request.labels.*.name, 'CI ubuntu-2004')
    uses: ./.github/workflows/trigger-remote-reusable-workflow.yml
    permissions:
      checks: write
      pull-requests: write
    with:
      repo_owner: 'shamil-mubarakshin'
      repo_name: 'azure-workflows'
      image_type: 'ubuntu2004'
    secrets: inherit
